apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server-dep
  labels:
    app: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: gcr.io/re-play-420511/discovery-server:44928aab9a391903d26744d69725ddbba6471ad2
          ports:
            - containerPort: 8761 # Assuming Eureka default port is 8761
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: discovery-server
spec:
  scaleTargetRef:
    kind: Deployment
    name: discovery-server-dep
  maxReplicas: 3
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: ClusterIP
  ports:
    - port: 8761 # Assuming Eureka default port is 8761
  selector:
    app: discovery-server
